### ISSUE TITLE
CMake Error: cryptonote/src/version.h.in does not exist.

### ISSUE THREAD

**Issue by ArtRaptors** [chavezcoin-project/chavezcoinwallet#2]
How to fix this error? 

CMake Error: File /home/asus/Desktop/chavezcoinwallet-master/cryptonote/src/version.h.in does not exist.
CMake Error at CMakeLists.txt:44 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!
See also "/home/asus/Desktop/chavezcoinwallet-master/CMakeFiles/CMakeOutput.log".
See also "/home/asus/Desktop/chavezcoinwallet-master/CMakeFiles/CMakeError.log".

**Comment by servc4** [comment]
Hi 
you need to place your cryptonote source to "/home/asus/Desktop/chavezcoinwallet-master" folder as "cryptonote" or make a symbolic link...
ln -s ../path-to-cryptonote-source cryptonote


 Regards
